In [1]:
!cd .. && mkdir build
!cd ../build/ && rm -rf *
!cd ../build && cmake \
  -DPYTHON_EXECUTABLE="$(which python)" \
  -DCMAKE_BUILD_TYPE=Release ..
!cd ../build && make install

mkdir: cannot create directory ‘build’: File exists
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Release mode
-- Found PythonInterp: /home/oscar/anaconda3/envs/tp2/bin/python (found version "3.6.5") 
-- Found PythonLibs: /home/oscar/anaconda3/envs/tp2/lib/libpython3.6m.so
-- pybind11 v2.2.4
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMAKE_INSTALL_PREFIX=/home/oscar/Documents/MetNum/tp2/tp2-metodos/tp2
-- Confi

In [2]:
# Verifico la correcta instalación. Si no falla el import está OK
!pwd
!python --version
import metnum

/home/oscar/Documents/MetNum/tp2/tp2-metodos/tp2/notebooks
Python 3.6.5 :: Anaconda, Inc.


In [3]:
import pandas as pd

df = pd.read_csv("expectativa_de_vida.csv")
display(df)

Unnamed: 0                             Country  Life expectancy  \
0             0                         Afghanistan         58.19375   
1             1                             Albania         75.15625   
2             2                             Algeria         73.61875   
3             3                              Angola         49.01875   
4             4                 Antigua and Barbuda         75.05625   
..          ...                                 ...              ...   
178         188  Venezuela (Bolivarian Republic of)         73.38750   
179         189                            Viet Nam         74.77500   
180         190                               Yemen         63.86250   
181         191                              Zambia         53.90625   
182         192                            Zimbabwe         50.48750   

     Adult Mortality  infant deaths   Alcohol  percentage expenditure  \
0           269.0625        78.2500  0.014375               34.960110   
1            45.0625         0.6875  4.848750              193.259091   
2           108.1875        20.3125  0.406667              236.185241   
3           328.5625        83.7500  5.740667              102.100268   
4           127.5000         0.0000  7.949333             1001.585226   
..               ...            ...       ...                     ...   
178         163.0000         9.3750  7.420000                0.000000   
179         126.5625        29.1875  3.087333                0.000000   
180         211.8125        39.3750  0.047333                0.000000   
181         354.3125        33.4375  2.239333               89.650407   
182         462.3750        26.5625  4.482000               20.364271   

     Hepatitis B    Measles       BMI  ...  Total expenditure  Diphtheria  \
0      64.562500  2362.2500  15.51875  ...           8.252500     52.3125   
1      98.000000    53.3750  49.06875  ...           5.945625     98.0625   
2      78.000000  1943.8750  48.74375  ...           4.604000     91.8750   
3      70.222222  3561.3125  18.01875  ...           3.919333     47.6875   
4      98.266667     0.0000  38.42500  ...           4.791333     98.3125   
..           ...        ...       ...  ...                ...         ...   
178    66.250000   165.0000  54.48750  ...           4.998667     68.5000   
179    87.538462  4232.9375  11.18750  ...           5.977333     91.7500   
180    55.687500  2761.1875  33.48750  ...           5.005333     72.6250   
181    69.818182  6563.8125  17.45000  ...           5.824000     74.2500   
182    70.562500   923.0000  25.13750  ...           6.158667     75.1875   

     HIV/AIDS          GDP    Population  thinness  1-19 years  \
0     0.10000   340.015425  9.972260e+06              16.58125   
1     0.10000  2119.726679  6.969116e+05               1.61875   
2     0.10000  2847.853392  2.164983e+07               6.09375   
3     2.36875  1975.143045  1.014710e+07               6.19375   
4     0.12500  9759.305728           NaN               3.42500   
..        ...          ...           ...                   ...   
178   0.10000          NaN           NaN               1.65000   
179   0.14375          NaN           NaN              14.92500   
180   0.10000          NaN           NaN              13.83125   
181  11.93125   811.811841  6.260246e+06               6.88125   
182  23.26250   410.980194  8.021343e+06               7.01250   

     thinness 5-9 years  Income composition of resources  Schooling  \
0              15.58125                         0.415375    8.21250   
1               1.70000                         0.709875   12.13750   
2               5.97500                         0.694875   12.71250   
3               6.66875                         0.458375    8.04375   
4               3.37500                         0.488625    8.84375   
..                  ...                              ...        ...   
178             1.56250                         

In [4]:
lsq = metnum.LeastSquareMethod()

In [5]:
import numpy as np

unos = np.ones(183)
x = df["Adult Mortality"].values.reshape(-1, 1)
y = df["Life expectancy"].values.reshape(-1, 1)
matriz = np.column_stack((unos, x))

In [6]:
lsq.ajustar(matriz, y)

array([83.33433067, -0.08561713])

In [7]:
matriz.shape

(183, 2)

In [8]:
import statsmodels.api as sm

In [9]:
regresion = sm.OLS(y, matriz).fit()

In [10]:
regresion.params

array([83.33433067, -0.08561713])

In [11]:
x1 = df["Adult Mortality"].values.reshape(-1, 1)
x2 = df["infant deaths"].values.reshape(-1, 1)

In [12]:
matriz = np.column_stack((unos, x1, x2))

In [13]:
matriz

array([[1.0000000e+00, 2.6906250e+02, 7.8250000e+01],
       [1.0000000e+00, 4.5062500e+01, 6.8750000e-01],
       [1.0000000e+00, 1.0818750e+02, 2.0312500e+01],
       [1.0000000e+00, 3.2856250e+02, 8.3750000e+01],
       [1.0000000e+00, 1.2750000e+02, 0.0000000e+00],
       [1.0000000e+00, 1.0600000e+02, 1.0125000e+01],
       [1.0000000e+00, 1.1737500e+02, 1.0000000e+00],
       [1.0000000e+00, 6.3187500e+01, 1.0000000e+00],
       [1.0000000e+00, 6.5750000e+01, 0.0000000e+00],
       [1.0000000e+00, 1.1518750e+02, 6.0625000e+00],
       [1.0000000e+00, 1.5206250e+02, 0.0000000e+00],
       [1.0000000e+00, 6.5375000e+01, 0.0000000e+00],
       [1.0000000e+00, 1.4137500e+02, 1.5362500e+02],
       [1.0000000e+00, 7.7625000e+01, 0.0000000e+00],
       [1.0000000e+00, 2.1875000e+02, 5.6250000e-01],
       [1.0000000e+00, 7.0187500e+01, 2.5000000e-01],
       [1.0000000e+00, 1.5550000e+02, 0.0000000e+00],
       [1.0000000e+00, 2.6937500e+02, 2.5000000e+01],
       [1.0000000e+00, 2.302

In [14]:
lsq.ajustar(matriz, y)

array([ 8.34286488e+01, -8.45545925e-02, -8.86035042e-03])

In [15]:
regresion2 = sm.OLS(y, matriz).fit()

In [16]:
regresion2.params

array([ 8.34286488e+01, -8.45545925e-02, -8.86035042e-03])